import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', 'Inter', ...defaultTheme.fontFamily.sans],
                'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
                'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
                'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'label-sm': ['Inter', 'sans-serif'],
                'tabular-mono': ['Inter', 'monospace'],
            },
            colors: {
                "surface-dim": "#d2d9f4",
                "on-primary-fixed-variant": "#93000b",
                "tertiary": "#614000",
                "surface-container-highest": "#dae2fd",
                "inverse-primary": "#ffb4ab",
                "surface-container-high": "#e2e7ff",
                "on-surface": "#131b2e",
                "surface-container-lowest": "#ffffff",
                "on-background": "#131b2e",
                "primary": "#93000b",
                "outline": "#8f6f6c",
                "surface-variant": "#dae2fd",
                "on-secondary-container": "#007233",
                "secondary": "#006d30",
                "surface-container-low": "#f2f3ff",
                "inverse-on-surface": "#eef0ff",
                "on-tertiary": "#ffffff",
                "surface": "#faf8ff",
                "on-secondary-fixed": "#00210a",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#ffb4ab",
                "secondary-container": "#92f5a4",
                "on-surface-variant": "#5b403d",
                "primary-fixed": "#ffdad6",
                "secondary-fixed-dim": "#79db8d",
                "background": "#faf8ff",
                "surface-bright": "#faf8ff",
                "on-secondary-fixed-variant": "#005323",
                "on-primary-container": "#ffcdc7",
                "tertiary-fixed": "#ffddb0",
                "surface-tint": "#b91c1c",
                "on-secondary": "#ffffff",
                "tertiary-container": "#805600",
                "on-primary-fixed": "#410002",
                "on-tertiary-fixed": "#281800",
                "on-tertiary-fixed-variant": "#614000",
                "secondary-fixed": "#95f8a7",
                "tertiary-fixed-dim": "#ffba46",
                "error": "#ba1a1a",
                "on-tertiary-container": "#ffd18f",
                "on-primary": "#ffffff",
                "outline-variant": "#e4beb9",
                "error-container": "#ffdad6",
                "on-error": "#ffffff",
                "primary-container": "#b91c1c",
                "surface-container": "#eaedff",
                "inverse-surface": "#283044",
                // Backward compatibility colors
                'bumdes-cream': '#faf8ff',
                'bumdes-border': '#CBD5E1',
                'bumdes-dark': '#131b2e',
                'bumdes-muted': '#5b403d',
            },
            spacing: {
                "gutter-desktop": "1.5rem",
                "space-xs": "0.25rem",
                "gutter": "1rem",
                "margin-desktop": "2rem",
                "space-sm": "0.5rem",
                "margin-tablet": "1.5rem",
                "space-lg": "1.25rem",
                "space-md": "0.75rem",
                "space-xl": "2rem",
                "margin": "1rem",
                "gutter-tablet": "1.25rem",
            },
        },
    },

    plugins: [forms],
};
